#!/usr/bin/env bash
# =============================================================================
# import_curation.sh
# Generates Terraform import blocks for JFrog Curation resources only:
#   - Curation Conditions  (xray_custom_curation_condition — custom only, by numeric id)
#   - Curation Policies    (xray_curation_policy — by numeric id)
#
# Requirements: curl, jq, Terraform 1.5+
#
# Usage:
#   export ARTIFACTORY_URL="https://your-org.jfrog.io"
#   export ARTIFACTORY_TOKEN="your-access-token"
#   ./import_curation.sh
#
# Output:
#   curation_imports.tf — feed into:
#   terraform plan -generate-config-out=curation_existingimported.tf
# =============================================================================

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
ARTIFACTORY_URL="${ARTIFACTORY_URL:?Please set ARTIFACTORY_URL}"
ARTIFACTORY_TOKEN="${ARTIFACTORY_TOKEN:?Please set ARTIFACTORY_TOKEN}"
OUTPUT_FILE="curation_imports.tf"
PAGE_SIZE=100

# ── Colors ────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

# ── Helpers ───────────────────────────────────────────────────────────────────
tf_name() {
  echo "$1" | sed 's/[^a-zA-Z0-9_]/_/g'
}

xray_get() {
  local path="$1"
  curl -sf \
    -H "Authorization: Bearer ${ARTIFACTORY_TOKEN}" \
    -H "Content-Type: application/json" \
    "${ARTIFACTORY_URL}/xray/api${path}"
}

# Deduplication via temp file — prevents duplicate import blocks
SEEN_IMPORTS_FILE=$(mktemp)

write_import() {
  local resource="$1"
  local name="$2"
  local id="$3"
  local key="${resource}.${name}"

  if grep -qxF "$key" "$SEEN_IMPORTS_FILE" 2>/dev/null; then
    echo -e "   ${YELLOW}⏭️  Skipping duplicate: ${key}${NC}"
    return
  fi
  echo "$key" >> "$SEEN_IMPORTS_FILE"

  cat >> "$OUTPUT_FILE" <<EOF
import {
  to = ${resource}.${name}
  id = "${id}"
}

EOF
}

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║    JFrog Curation Import Generator               ║${NC}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# ── Init output file ──────────────────────────────────────────────────────────
echo "# Generated by import_curation.sh" >  "$OUTPUT_FILE"
echo "# $(date)"                          >> "$OUTPUT_FILE"
echo "# Source: ${ARTIFACTORY_URL}"       >> "$OUTPUT_FILE"
echo ""                                   >> "$OUTPUT_FILE"

TOTAL=0

# ── 1. Curation Conditions ────────────────────────────────────────────────────
echo -e "⏳ Fetching curation conditions..."

curation_cond_total=0
offset=0

echo "# ── Curation Conditions (jfrog/xray) ──────────────────────────────────────" >> "$OUTPUT_FILE"
echo "# Import ID = numeric id from API (not the name)"                              >> "$OUTPUT_FILE"
echo ""                                                                              >> "$OUTPUT_FILE"

while true; do
  page_json=$(xray_get "/v1/curation/conditions?is_custom=true&num_of_rows=${PAGE_SIZE}&offset=${offset}")
  page_count=$(echo "$page_json" | jq '.data | length')

  if [[ "$page_count" -eq 0 ]]; then
    break
  fi

  while IFS= read -r line; do
    condid=$(echo "$line"   | jq -r '.id'   | tr -d '[:space:]')
    condname=$(echo "$line" | jq -r '.name' | tr -d '[:space:]')
    template=$(echo "$line" | jq -r '.condition_template_id // "unknown"' | tr -d '[:space:]')
    name=$(tf_name "$condname")

    write_import "xray_custom_curation_condition" "$name" "$condid"
    echo -e "   ✅ ${condname} (id=${condid}, template=${template})"
    ((curation_cond_total++)) || true
  done < <(echo "$page_json" | jq -c '.data[]')

  if [[ "$page_count" -lt "$PAGE_SIZE" ]]; then
    break
  fi
  ((offset += PAGE_SIZE)) || true
done

((TOTAL += curation_cond_total)) || true
echo -e "   ${GREEN}✅ ${curation_cond_total} curation conditions imported${NC}"
echo ""

# ── 2. Curation Policies ──────────────────────────────────────────────────────
echo -e "⏳ Fetching curation policies..."

curation_pol_total=0
offset=0

echo ""                                                                              >> "$OUTPUT_FILE"
echo "# ── Curation Policies (jfrog/xray) ────────────────────────────────────────" >> "$OUTPUT_FILE"
echo "# Import ID = numeric id from API (not the name)"                             >> "$OUTPUT_FILE"
echo ""                                                                              >> "$OUTPUT_FILE"

while true; do
  page_json=$(xray_get "/v1/curation/policies?num_of_rows=${PAGE_SIZE}&offset=${offset}")
  page_count=$(echo "$page_json" | jq '.data | length')

  if [[ "$page_count" -eq 0 ]]; then
    break
  fi

  while IFS= read -r line; do
    polid=$(echo "$line"   | jq -r '.id'   | tr -d '[:space:]')
    polname=$(echo "$line" | jq -r '.name' | tr -d '[:space:]')
    name=$(tf_name "$polname")

    write_import "xray_curation_policy" "$name" "$polid"
    echo -e "   ✅ ${polname} (id=${polid})"
    ((curation_pol_total++)) || true
  done < <(echo "$page_json" | jq -c '.data[]')

  if [[ "$page_count" -lt "$PAGE_SIZE" ]]; then
    break
  fi
  ((offset += PAGE_SIZE)) || true
done

((TOTAL += curation_pol_total)) || true
echo -e "   ${GREEN}✅ ${curation_pol_total} curation policies imported${NC}"

# ── Cleanup ───────────────────────────────────────────────────────────────────
rm -f "$SEEN_IMPORTS_FILE"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${CYAN}════════════════════════════════════════════════════${NC}"
echo -e "  ${BOLD}Resource                    Count${NC}"
echo -e "  ──────────────────────────────────────────────────"
echo -e "  Curation Conditions       : ${curation_cond_total}"
echo -e "  Curation Policies         : ${curation_pol_total}"
echo -e "  ──────────────────────────────────────────────────"
echo -e "  ${BOLD}Total import blocks       : ${TOTAL}${NC}"
echo -e "  Output file               : ${OUTPUT_FILE}"
echo -e "${BOLD}${CYAN}════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. terraform init"
echo "  2. terraform plan -generate-config-out=curation_existingimported.tf"
echo "  3. terraform apply"
echo ""
